### ISSUE TITLE
KeyError: 'fcn_logits' in KittiSeg

### ISSUE THREAD

**Issue by maxtom** [MarvinTeichmann/MultiNet#10]
**problem when run `python train.py --hypes hypes/multinet2.json`**

14:17:55,887 INFO Creating Summary for: fc7/weights
2017-03-17 14:17:55,912 INFO Creating Summary for: fc7/biases
2017-03-17 14:17:55,956 INFO Creating Summary for: score_fr/weights
2017-03-17 14:17:55,980 INFO Creating Summary for: score_fr/biases
2017-03-17 14:17:56,026 INFO Creating Summary for: upscore2/up_filter
2017-03-17 14:17:56,063 INFO Creating Summary for: score_pool4/weights
2017-03-17 14:17:56,140 INFO Creating Summary for: score_pool4/biases
2017-03-17 14:17:56,184 INFO Creating Summary for: upscore4/up_filter
2017-03-17 14:17:56,223 INFO Creating Summary for: score_pool3/weights
2017-03-17 14:17:56,250 INFO Creating Summary for: score_pool3/biases
2017-03-17 14:17:56,301 INFO Creating Summary for: upscore32/up_filter
{'images': <tf.Tensor 'Inputs/ExpandDims:0' shape=(1, ?, ?, 3) dtype=float32>, 'feed2': <tf.Tensor 'pool4:0' shape=(1, ?, ?, 512) dtype=float32>, 'fcn_in': <tf.Tensor 'dropout_1/mul:0' shape=(1, ?, ?, 4096) dtype=float32>, 'feed4': <tf.Tensor 'pool3:0' shape=(1, ?, ?, 256) dtype=float32>}
Traceback (most recent call last):
  File "train.py", line 614, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 593, in main
    subhypes, submodules, subgraph, tv_sess = build_united_model(hypes)
  File "train.py", line 533, in build_united_model
    first_iter)
  File "train.py", line 133, in build_training_graph
    decoded_logits = objective.decoder(hypes, logits, train=True)
  File "/home/hustxly/MultiNet/submodules/KittiSeg/hypes/../decoder/kitti_multiloss.py", line 49, in decoder
    decoded_logits['logits'] = logits['fcn_logits']
KeyError: 'fcn_logits'

**And I checkout the logist's outputs, there is no fcn_logits keywords**

{'images': <tf.Tensor 'Inputs/ExpandDims:0' shape=(1, ?, ?, 3) dtype=float32>, 'feed2': <tf.Tensor 'pool4:0' shape=(1, ?, ?, 512) dtype=float32>, 'fcn_in': <tf.Tensor 'dropout_1/mul:0' shape=(1, ?, ?, 4096) dtype=float32>, 'feed4': <tf.Tensor 'pool3:0' shape=(1, ?, ?, 256) dtype=float32>}

**Comment by MarvinTeichmann** [comment]
Hi Maxtom,

thanks for letting me know. This was an issue with submodule Versions.  Commit 6efeedf should fix it.

Please run 
```
git pull
git submodule update
```

To update all submodules to the correct Version.
