### ISSUE TITLE
Data URL not provided

### ISSUE THREAD

**Issue by cmuhao** [MarvinTeichmann/MultiNet#13]
After I downloaded the data using data_download.py, I got this error when I train the model.
```

ubuntu@ip-172-30-5-78:~/didicompetetion/Hao/MultiNet$ sudo python train.py --hypes hypes/multinet2.json
2017-03-21 03:08:13,093 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/ubuntu/tv-plugins'.
2017-03-21 03:08:13,093 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-03-21 03:08:13,093 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-03-21 03:08:13,093 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-03-21 03:08:13,093 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-03-21 03:08:13,093 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-03-21 03:08:13,094 INFO f: <open file 'hypes/multinet2.json', mode 'r' at 0x7fd421d44b70>
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-03-21 03:08:13,097 INFO Initialize training folder
2017-03-21 03:08:13,097 INFO f: <open file u'/home/ubuntu/didicompetetion/Hao/MultiNet/hypes/../submodules/KittiSeg/hypes/KittiSeg.json', mode 'r' at 0x7fd420796540>
2017-03-21 03:08:13,099 ERROR Data URL for Kitti Data not provided.
2017-03-21 03:08:13,099 ERROR Please visit: http://www.cvlibs.net/download.php?file=data_road.zip
2017-03-21 03:08:13,099 ERROR and request Kitti Download link.
2017-03-21 03:08:13,099 ERROR Enter URL in hypes/kittiSeg.json
```
I could find the json file, but the Kitti_url is empty, if I put the url retrieved from the step-4, its not working.
Any suggestion on it?

**Comment by MarvinTeichmann** [comment]
Did you run `python download_data.py --kitti_url URL_YOU_RETRIEVED`? This should download and prepare all data.

**Comment by cmuhao** [comment]
yeah I used `python download_data.py --kitti_url URL_YOU_RETRIEVED` to retrieve data. And it said all done. the problem showed up when try to use train.py. And I tracked the error line to `KittiSeg.json` found the URL is empty.

**Comment by MarvinTeichmann** [comment]
This message comes, when no folder `data_road` cannot be found. Can you check whether there is a folder `data_road` in `RUNS` or `$TV_DIR_RUNS`?

**Comment by cmuhao** [comment]
my data_road is in `MultiNet/DATA`, is it supposed to be in `RUNS/`?

**Comment by MarvinTeichmann** [comment]
No, sry it should be in `DATA`. Is there a dir `data_road`?

**Comment by cmuhao** [comment]
yep. there is.
```
ubuntu@ip-172-30-5-78:~/didicompetetion/Hao/MultiNet/DATA$ ls
data_road  data_road.zip  KittiBox  vgg16.npy
```

**Comment by cmuhao** [comment]
And I after I put the URL manually, new error occurred:
```
2017-03-21 14:58:42,749 INFO Initialize training folder
2017-03-21 14:58:42,749 INFO f: <open file u'/home/ubuntu/didicompetetion/Hao/MultiNet/hypes/../submodules/KittiSeg/hypes/KittiSeg.json', mode 'r' at 0x7fa81a9dd540>
Traceback (most recent call last):
  File "train.py", line 615, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 594, in main
    subhypes, submodules, subgraph, tv_sess = build_united_model(hypes)
  File "train.py", line 512, in build_united_model
    subhypes[model] = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 17 column 5 (char 544)
```
It seems the URL is not readable?

**Comment by MarvinTeichmann** [comment]
The code tries to download the data in kitti_seg_input. All files seams to be there. The routine should be skipped at this : [line](
https://github.com/MarvinTeichmann/KittiSeg/blob/16168601f6a289dbe72ae6a766857b9124185090/inputs/kitti_seg_input.py#L56)

Can you check, why if `os.path.exists(vgg_weights) and os.path.exists(kitti_road_dir)` returns false? Is  `data_dir` set correctly?

**Comment by MarvinTeichmann** [comment]
Hi, I think I found the issue. Can you try

**Comment by cmuhao** [comment]
no, still not working
```
2017-03-21 15:18:19,534 INFO Initialize training folder
2017-03-21 15:18:19,534 INFO f: <open file u'/home/ubuntu/didicompetetion/Hao/MultiNet/hypes/../submodules/KittiSeg/hypes/KittiSeg.json', mode 'r' at 0x7f112a85d540>
Traceback (most recent call last):
  File "train.py", line 616, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 595, in main
    subhypes, submodules, subgraph, tv_sess = build_united_model(hypes)
  File "train.py", line 513, in build_united_model
    subhypes[model] = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 17 column 5 (char 544)
```

**Comment by MarvinTeichmann** [comment]
Can you use the unmodified hype? The quoted issue indicates that your hype does not follow the `.json` specification (Forgot using quotes when pasting the kitti url?).

**Comment by cmuhao** [comment]
yeah that error fixed! but another one showed up.. lol
```
Traceback (most recent call last):
  File "train.py", line 618, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 597, in main
    subhypes, submodules, subgraph, tv_sess = build_united_model(hypes)
  File "train.py", line 537, in build_united_model
    first_iter)
  File "train.py", line 133, in build_training_graph
    decoded_logits = objective.decoder(hypes, logits, train=True)
  File "/home/ubuntu/didicompetetion/Hao/MultiNet/submodules/KittiSeg/hypes/../decoder/kitti_multiloss.py", line 48, in decoder
    decoded_logits['logits'] = logits['fcn_logits']
KeyError: 'fcn_logits'
```

And it happened after running several layers.

**Comment by MarvinTeichmann** [comment]
This looks as if you are using an old version of KittiSeg. Try updating all submodules by running:

```
git pull
git submodule update
```

**Comment by cmuhao** [comment]
yeah fixed  after review #10. One question, it asked like this:
`ERROR File '/home/ubuntu/didicompetetion/Hao/MultiNet/hypes/../DATA/weights/vgg16.npy' not found. Download it from ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy` 
`ERROR File '/home/ubuntu/didicompetetion/Hao/MultiNet/hypes/../DATA/vgg16.npy' not found. Download it from ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy`

So I just put `vgg16.npy` both in `DATA/` and `DATA/weights/`, that makes me confused.

**Comment by MarvinTeichmann** [comment]
Yeah, the different submodules read the data from different location. Should properly fix this. For now you can avoid downloading it twice by creating a symlink `ln -s vgg16.npy weights/vgg16.npy` or vice versa.

**Comment by cmuhao** [comment]
cool, Ill close this issue, thanks for helping me! :)
