### ISSUE TITLE
demo.py doesn't work

### ISSUE THREAD

**Issue by iliTheFallen** [MarvinTeichmann/MultiNet#19]
Hello,

After I installed all required modules, and followed the steps you had specified; I got the following exception. Would you mind helping me to run? Thanks.

`(tensorflow)ilithefallen@ubuntu:~/Documents/phdThesis/libs/MultiNet$ python demo.py --gpus 0 --input data/demo/um_000005.png
2017-05-03 18:36:22,177 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/ilithefallen/tv-plugins'.
2017-05-03 18:36:22,177 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-05-03 18:36:22,177 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-05-03 18:36:22,177 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-05-03 18:36:22,177 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-05-03 18:36:22,177 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-05-03 18:36:22,179 INFO GPUs are set to: 0
2017-05-03 18:36:22,179 INFO Download URL: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/MultiNet_ICCV.zip
2017-05-03 18:36:22,179 INFO Download DIR: RUNS
>> Downloading MultiNet_ICCV.zip 100.0%
2017-05-03 18:55:18,499 INFO Extracting MultiNet_pretrained.zip
2017-05-03 18:55:31,855 INFO f: <_io.TextIOWrapper name='RUNS/MultiNet_ICCV/hypes.json' mode='r' encoding='UTF-8'>
2017-05-03 18:55:31,855 INFO f: <_io.TextIOWrapper name='RUNS/MultiNet_ICCV/road/hypes.json' mode='r' encoding='UTF-8'>
2017-05-03 18:55:31,864 INFO f: <_io.TextIOWrapper name='RUNS/MultiNet_ICCV/detection/hypes.json' mode='r' encoding='UTF-8'>
Traceback (most recent call last):
  File "demo.py", line 413, in <module>
    tf.app.run()
  File "/home/ilithefallen/tensorflow/lib/python3.4/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 311, in main
    load_out = load_united_model(logdir)
  File "demo.py", line 254, in load_united_model
    postfix=model)
  File "incl/tensorvision/utils.py", line 213, in load_modules_from_logdir
    data_input = imp.load_source("input_%s" % postfix, f)
  File "/home/ilithefallen/tensorflow/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "RUNS/MultiNet_ICCV/detection/data_input.py", line 22, in <module>
    from utils.data_utils import (annotation_jitter, annotation_to_h5)
  File "/home/ilithefallen/Documents/phdThesis/libs/MultiNet/submodules/KittiBox/incl/utils/data_utils.py", line 11, in <module>
    import annolist.AnnotationLib as al
ImportError: No module named 'annolist'`

**Comment by MarvinTeichmann** [comment]
Looks like the code does not find the module annolist. It should be in the folder KittiBox. Try to locate the file and see why the code cant find it.
