### ISSUE TITLE
trying to run demo.py getting import PalLib not found in AnnotationLib.py

### ISSUE THREAD

**Issue by rnunziata** [MarvinTeichmann/MultiNet#22]
trying to run demo.py getting import PalLib not found in AnnotationLib.py. Unable to locate this lib for install. Also had to add 
sys.path.append("..path...) to data_utils.py so it could find AnnotationLib.py.

**Comment by villanuevab** [comment]
I am encountering the same issue after trying the same steps. I believe this is also related to #19. It appears that the modules are not being symlinked properly.

**Comment by MarvinTeichmann** [comment]
Did you initialize all submodules? Try 
`git clone --recursive git@github.com:MarvinTeichmann/MultiNet.git`

I am not having this issue, I tried cloned MultiNet into a fresh virtuelenv and it works fine.

**Comment by villanuevab** [comment]
Hi @MarvinTeichmann, thank you for your quick response. I did try that command. I am using an Anaconda vitualenv with Python 3.6.1 and Tensorflow 1.1.0. Attempting to run `demo.py` yields: 
```
2017-05-29 23:24:17,400 INFO Extracting MultiNet_pretrained.zip
2017-05-29 23:24:54,333 INFO Loading model from: RUNS/MultiNet_ICCV
2017-05-29 23:24:54,333 INFO f: <_io.TextIOWrapper name='RUNS/MultiNet_ICCV/hypes.json' mode='r' encoding='UTF-8'>
2017-05-29 23:24:54,335 INFO f: <_io.TextIOWrapper name='RUNS/MultiNet_ICCV/detection/hypes.json' mode='r' encoding='UTF-8'>
Traceback (most recent call last):
  File "demo.py", line 426, in <module>
    tf.app.run()
  File "/Users/###/miniconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 313, in main
    load_out = load_united_model(logdir)
  File "demo.py", line 254, in load_united_model
    postfix=model)
  File "incl/tensorvision/utils.py", line 213, in load_modules_from_logdir
    data_input = imp.load_source("input_%s" % postfix, f)
  File "/Users/###/miniconda3/envs/python3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "RUNS/MultiNet_ICCV/detection/data_input.py", line 22, in <module>
    from utils.data_utils import (annotation_jitter, annotation_to_h5)
  File "/Users/###/MultiNet/submodules/KittiBox/incl/utils/data_utils.py", line 11, in <module>
    import annolist.AnnotationLib as al
ModuleNotFoundError: No module named 'annolist'
```

I ran the following commands: 
1. `git clone --recursive git@github.com:MarvinTeichmann/MultiNet.git` runs without error
2. `pip install -r requirements.txt` runs without error
3. `cd submodules/KittiBox/submodules/utils/ && make` yields the error: 
```
pip install runcython
Requirement already satisfied: runcython in /Users/###/miniconda3/envs/python3/lib/python3.6/site-packages
Requirement already satisfied: Cython>=0.10 in /Users/###/miniconda3/envs/python3/lib/python3.6/site-packages (from runcython)
makecython++ stitch_wrapper.pyx "" "stitch_rects.cpp ./hungarian/hungarian.cpp"
Package python was not found in the pkg-config search path.
Perhaps you should add the directory containing `python.pc'
to the PKG_CONFIG_PATH environment variable
No package 'python' found
stitch_wrapper.cpp:4:10: fatal error: 'Python.h' file not found
#include "Python.h"
         ^
1 error generated.
make: *** [all] Error 1
```

**Comment by villanuevab** [comment]
Ah, the code runs with Python 2.7.
