### ISSUE TITLE
demo getting tensorflow error processing weights

### ISSUE THREAD

**Issue by rnunziata** [MarvinTeichmann/MultiNet#23]
Getting an issue trying to read the vgg16 weights. I am running cuda-8 tensorflow 10 on ubuntu 16  with python3. Appear to be version conflict with saved npy format.
```
Traceback (most recent call last):
  File "demo.py", line 413, in <module>
    tf.app.run()
  File "/home/richard/.virtualenvs/cvp3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "demo.py", line 311, in main
    load_out = load_united_model(logdir)
  File "demo.py", line 273, in load_united_model
    logits = modules['arch'].inference(hypes, image, train=False)
  File "RUNS/MultiNet_ICCV/detection/architecture.py", line 28, in inference
    random_init_fc8=True)
  File "/home/richard/opencv3-p3-code/not_working_yet/MultiNet/submodules/KittiClass/incl/tensorflow_fcn/fcn8_vgg.py", line 59, in build
    red, green, blue = tf.split(rgb, 3, 3)
  File "/home/richard/.virtualenvs/cvp3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 918, in split
    name=name)
  File "/home/richard/.virtualenvs/cvp3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2239, in _split
    num_split=num_split, name=name)
  File "/home/richard/.virtualenvs/cvp3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 463, in apply_op
    (prefix, dtypes.as_dtype(input_arg.type).name))
TypeError: Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

```

**Comment by rnunziata** [comment]
Seems to be related to changes in tensorflow v0.12.0. split call signature has changed
