### ISSUE TITLE
About download_data.py

### ISSUE THREAD

**Issue by mingminzhen** [MarvinTeichmann/MultiNet#4]
I use 
   python download_data.py  --kitti_url http://www.cvlibs.net/download.php?file=data_road.zip
                      or
   python download_data.py  --kitti_url http://kitti.is.tue.mpg.de/kitti/data_road.zip
(http://kitti.is.tue.mpg.de/kitti/data_road.zip is the url i get after email verified)
Then i get the error
2017-03-11 22:30:28,331 WARNING File: DATA/vgg16.npy exists.
2017-03-11 22:30:28,331 WARNING Please delete to redownload VGG weights.
2017-03-11 22:30:28,331 ERROR Wrong url.
2017-03-11 22:30:28,331 ERROR Please visit: http://www.cvlibs.net/download.php?file=data_road.zip
2017-03-11 22:30:28,331 ERROR and request Kitti Download link.
2017-03-11 22:30:28,331 ERROR Rerun scipt using'python download_data.py --kitti_url [url]'

i check the source code in download_data.py, the right url is ended with 'kitti/data_object_image_2.zip'. It is a little confused. How can i get the right url ?

**Comment by MarvinTeichmann** [comment]
Hi,

I now put a correct Version of the download data script in the repository. The correct URL is http://kitti.is.tue.mpg.de/kitti/data_road.zip. Although it does not really matter. The script will download various kitti data files and craft the URLs as needed. Sorry that it is so complicated with the Kitti data.

Marvin

**Comment by mingminzhen** [comment]
I tried it. But some files doesn't exist in the data directory.
"train.txt", "val.txt", "testing.txt", "train3.txt", "val3.txt" these 5 files are missing.
where can i get them?

the printed error is : 
Traceback (most recent call last):
  File "download_data.py", line 175, in <module>
    main()
  File "download_data.py", line 132, in main
    copy2(filename, target_dir)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'data/train.txt'

**Comment by mingminzhen** [comment]
I find them. you put these files in the data directory other than submodules/KittiBox/data directory.

**Comment by MarvinTeichmann** [comment]
Did you pull the latest commit? I copied all of those files in the [data ](https://github.com/MarvinTeichmann/MultiNet/tree/master/data) directory.

**Comment by mingminzhen** [comment]
yes, i get them. thanks.
