### ISSUE TITLE
No module named 'annolist'

### ISSUE THREAD

**Issue by Supradeep91** [MarvinTeichmann/MultiNet#45]
Hello, 

After successful completion of all the described steps, tried running the demo.py But it seems, "annolist" is not found. Could you please let me know how do I fix it. 

>> Downloading MultiNet_ICCV.zip 100.0%
2018-04-18 18:14:20,576 INFO Extracting MultiNet_pretrained.zip
2018-04-18 18:15:13,790 INFO Loading model from: RUNS/MultiNet_ICCV
2018-04-18 18:15:13,791 INFO f: <_io.TextIOWrapper name='RUNS/MultiNet_ICCV/hypes.json' mode='r' encoding='UTF-8'>
2018-04-18 18:15:13,793 INFO f: <_io.TextIOWrapper name='RUNS/MultiNet_ICCV/detection/hypes.json' mode='r' encoding='UTF-8'>
Traceback (most recent call last):
  File "demo.py", line 426, in <module>
    tf.app.run()
  File "/home/aev21/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "demo.py", line 313, in main
    load_out = load_united_model(logdir)
  File "demo.py", line 254, in load_united_model
    postfix=model)
  File "incl/tensorvision/utils.py", line 213, in load_modules_from_logdir
    data_input = imp.load_source("input_%s" % postfix, f)
  File "/home/aev21/anaconda3/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "RUNS/MultiNet_ICCV/detection/data_input.py", line 22, in <module>
    from utils.data_utils import (annotation_jitter, annotation_to_h5)
  File "PycharmProjects/MultiNet/submodules/KittiBox/incl/utils/data_utils.py", line 11, in <module>
    import annolist.AnnotationLib as al
ModuleNotFouldError: No module named 'annolist'

**Comment by Supradeep91** [comment]
Was trying with python instead of python2.
