### ISSUE TITLE
python demo.py  error

### ISSUE THREAD

**Issue by yghcats** [MarvinTeichmann/MultiNet#6]
Run command：python demo.py --gpus 0 --input data/demo/um_000005.png

error info：
2017-03-16 17:08:13,898 INFO f: <open file u'RUNS/MultiNet_pretrained/detection/hypes.json', mode 'r' at 0x7f3579424ed0>
Traceback (most recent call last):
  File "demo.py", line 407, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "demo.py", line 305, in main
    load_out = load_united_model(logdir)
  File "demo.py", line 249, in load_united_model
    postfix=model)
  File "incl/tensorvision/utils.py", line 213, in load_modules_from_logdir
    data_input = imp.load_source("input_%s" % postfix, f)
  File "RUNS/MultiNet_pretrained/detection/data_input.py", line 22, in <module>
    from utils.data_utils import (annotation_jitter, annotation_to_h5)
ImportError: No module named data_utils

What's wrong with this mistake?

thanks！

**Comment by maxtom** [comment]
I fix this problem by adding

`sys.path.append('submodules/KittiBox/submodules/')
sys.path.append('submodules/KittiSeg/incl/')
`
in the demo.py, it seems that the KittiBox's utils haven't been added into the sys path.

**Comment by zdx3578** [comment]
ubuntu 14 

ubuntu@ip-172-30-5-78:~/Downloads/MultiNet$ python demo.py --gpus 0 --input data/demo/um_000005.png
2017-03-17 03:46:15,485 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/ubuntu/tv-plugins'.
2017-03-17 03:46:15,486 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-03-17 03:46:15,486 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-03-17 03:46:15,486 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-03-17 03:46:15,486 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-03-17 03:46:15,486 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-03-17 03:46:15,486 INFO GPUs are set to: 0
2017-03-17 03:46:15,487 INFO Download URL: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/MultiNet_pretrained.zip
2017-03-17 03:46:15,487 INFO Download DIR: ./RUNS/MultiNet

download stop here  ; maybe no dir or not create dir

**Comment by maxtom** [comment]
@zdx3578 
Create RUNS dir under MultiNet cloud solve this problem.

**Comment by wumengfei** [comment]
![demo](https://cloud.githubusercontent.com/assets/14702302/24069892/ef67fd00-0bed-11e7-8823-9c547df0646b.jpg)
This log has been clogged for almost 20 minutes. Is it downloading?

**Comment by zdx3578** [comment]
@wumengfei  i pull a request ; fix this;  https://github.com/MarvinTeichmann/MultiNet/pull/11 ;  fixed;

**Comment by MarvinTeichmann** [comment]
Commit  5ba41b0 should fix the error. The manual include code is not required. The corresponding folders should be added automatically, if `base_path` is set correctly.

To run the update code do:
```
git pull
git submodules update
```

Please let me know whether there are still any issues after pulling the new code.
